### ISSUE TITLE
Error parsing wappalyzer html data

### ISSUE THREAD

**Issue by KathanP19** [ameenmaali/whoareyou#1]
```
$ echo "https://google.com" | whoareyou -debug
error parsing wappalyzer html data%!(EXTRA *errors.errorString=error parsing regexp: unexpected ): `(?:<div class="sf-toolbar[^>]+?>[^]+<span class="sf-toolbar-value">([\d.])+|<div id="sfwdt[^"]+" class="[^"]*sf-toolbar)`                                                                                         
value provided is not a slice of strings                                                                                                                   
)[https://google.com]: no matches found  
```

**Comment by ameenmaali** [comment]
Hey @KathanP19, thanks for sending this over. I did take a look, and it seems to be some odd regex provided from the Wappalyzer dataset that isn't cleanly converted when attempting to read it into Go's regexp package. It does seem to be the only one out of the few thousand it provides (https://github.com/AliasIO/wappalyzer/blob/master/src/apps.json#L11718). There's not really an easy way to handle this outside of what is already being done (moving on and ignoring that entry which means it won't break anything, but it won't be searched for). Let me know if you continue to experience more issues that make it unusable, but as of now I think it's worth it to just ignore this single entry rather than adding one-off functionality to handle this particular case.

**Comment by KathanP19** [comment]
how should I fix it, the tool is not working for any domain.

**Comment by ameenmaali** [comment]
Hey @KathanP19 - I was testing today and it worked for me. Only that single entry in Wappalyzer wasn’t being parsed properly. What issues are you seeing? Did you try it on other domains outside google.com?

**Comment by ameenmaali** [comment]
Hey @KathanP19 - I was testing today and it worked for me. Only that single entry in Wappalyzer wasn’t being parsed properly. What issues are you seeing? Did you try it on other domains outside google.com?

**Comment by KathanP19** [comment]
yes the same issue on other domain too same results, how do I fix it steps to follow?

**Comment by ameenmaali** [comment]
Are you just seeing that single error when using -debug? If so, that just means that single entry is not working (and it won’t work for any domain) in the entire Wappalyzer data set which is made up of thousands. If that particular entry is not important to you, I recommend just ignoring that error as it’s likely a non-issue. If it is important, then you’ll need to make edits to the Wappalyzer parsing logic to manually catch this edge case and reformat the regex provided because as of now it’s malformed for Go’s regex library.

**Comment by KathanP19** [comment]
When I do `echo "https://target.com" | whoareyou` I see nothing in output when I use with -debug I see that same result which I have share in the first comment for all domain that means the tool is not working , so if I want to edit this wappalyzer data file where do it get store as I tried to search for it in source files of whoareyou on my machine.

**Comment by ameenmaali** [comment]
Can you please help by running whoareyou against the below domains to see your output? I am curious how you are seeing no results, but I am :) - The data is never actually stored locally, it pulls it from the Wappalyzer repo every time it runs. Not a bad idea to add some functionality that stores it or runs it locally, however.

Here is the output I get for these domains:

```
$ echo "https://www.amazon.com" | whoareyou
[https://www.amazon.com]: [cs cart]

$ echo "https://www.yahoo.com" | whoareyou
[https://www.yahoo.com]: [cs cart, react]

$ echo "https://www.hackerone.com" | whoareyou
[https://www.hackerone.com]: [cs cart, react, google analytics]

$ echo "https://www.bugcrowd.com" | whoareyou
[https://www.bugcrowd.com]: [google tag manager, wordpress, wordpress, google font api]
```
